
server:
  port: 2001
spring:
  application:
    name: springboot3-gradle
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot3_demo
    username: root
    password: wtf0010.
    druid:
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: -1
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 5

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml
# Logger Config
logging:
  level:
    org.vivi.framework.gradle: debug
