
spring:
  application:
    name: JimuReport-example
  datasource:
    #    url: jdbc:mysql://${MYSQL_HOST:119.3.188.100}:${MYSQL_PORT:3306}/${MYSQL_DB:zhejiang_15minute}?useUnicode=true&amp&characterEncoding=UTF-8&amp&useSSL=false
    #    username: ${MYSQL_USERNAME:portal}
    #    password: ${MYSQL_PASSWORD:DreamPaas@0209}
    #    driver-class-name: com.mysql.jdbc.Driver
    #    hikari:
    #      minimum-idle: 3
    #      maximum-pool-size: 10
    #      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
    #      connection-test-query: SELECT 1
    url: jdbc:mysql://119.3.188.100:3306/jimureport?useUnicode=true&amp&characterEncoding=UTF-8&amp&useSSL=false
    username: root
    password: wtf0010.
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1

#持久层框架
minidao:
  base-package: org.jeecg.modules.jmreport.*
jeecg:
  # local|minio|alioss
  uploadType: local
  # local
  path:
    #文件路径
    upload: /opt/upload
  # alioss
  oss:
    endpoint: ??
    accessKey: ??
    secretKey: ??
    bucketName: jimureport
  # minio
  minio:
    minio_url: http://minio.jeecg.com
    minio_name: ??
    minio_pass: ??
    bucketName: ??
  #大屏报表参数设置
  jmreport:
    #多租户模式，默认值为空(created:按照创建人隔离、tenant:按照租户隔离)
    saasMode:
    # 平台上线安全配置
    firewall:
      # 数据源安全 (开启后，不允许使用平台数据源、SQL解析加签并且不允许查询数据库)
      dataSourceSafe: false
      # 低代码开发模式（dev:开发模式，prod:发布模式—关闭在线报表设计功能，分配角色admin、lowdeveloper可放开限制）
      lowCodeMode: dev
    # 展示列数
    col: 100
    # 展示行数
    row: 200
    #自定义API接口的前缀 #{api_base_path}和#{domainURL}的值
    apiBasePath: http://192.168.1.11:8085
    pageSize:
      - 10
      - 20
      - 30
      - 40
#输出sql日志
logging:
  level:
    org.jeecg.modules.jmreport: info
server:
  port: 8085