version: '3.6'
services:
  mysql-master:
    image: mysql:5.7
    container_name: mysql-master
    ports:
      - "3307:3307"
    volumes:
      - ./config/master.cnf:/etc/mysql/my.cnf
      - mysql-master-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wtf0010.

  mysql-slave1:
    image: mysql:5.7
    container_name: mysql-slave1
    ports:
      - "3308:3307"
    volumes:
      - ./config/slave1.cnf:/etc/mysql/my.cnf
      - mysql-slave1-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wtf0010.

  mysql-slave2:
    image: mysql:5.7
    container_name: mysql-slave2
    ports:
      - "3309:3307"
    volumes:
      - ./config/slave2.cnf:/etc/mysql/my.cnf
      - mysql-slave2-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wtf0010.

volumes:
  mysql-master-data:
  mysql-slave1-data:
  mysql-slave2-data: