spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.1:13306/nx_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      connect-timeout: 300000
# 报表配置
ureport:
  fileStoreDir: /home/nx-server/ureport-files
  debug: true
#  日志级别
logging:
  level:
    com.nonxun.ureport.mapper: error