server:
  port: 3002
spring:
  application:
    name: biz-service
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 119.3.188.100:8848
        service: biz-service


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["*"]