server:
  port: 3001
spring:
  application:
    name: consumer-service
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 119.3.188.100:8848
        service: consumer-service

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["*"]