
spring:
  application:
    name: springboot3-redis
  data:
    redis:
      host: 14.103.123.142
      port: 6379
      database: 0
      password: 123456
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0