server:
  port: 3001
spring:
  application:
    name: springboot3-redis
  data:
    redis:
      # Redis?????
      host: 192.168.100.131
      # Redis???????
      port: 6379
      # Redis?????????0?
      database: 0
      # Redis?????????????
      password: 123456
      # ??????????
      timeout: 3000ms
      # Redis?Java???
      lettuce:
        pool:
          # ???????????????????????8
          max-active: 8
          # ??????????????????????????-1
          max-wait: -1
          # ??????????? (???8)
          max-idle: 8
          # ??????????????0
          min-idle: 0