version: '3.7'
services:
  es01:
    image: elasticsearch:8.6.2
    container_name: es01
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      node.name: es01
      cluster.name: docker-cluster
      discovery.seed_hosts: es01,es02,es03
      cluster.initial_master_nodes: es01,es02,es03
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: false # es8引入https,为了开发方便关闭
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/node1/data:/usr/share/elasticsearch/data
    networks:
      - es-net

  es02:
    image: elasticsearch:8.6.2
    container_name: es02
    restart: unless-stopped
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      node.name: es02
      cluster.name: docker-cluster
      discovery.seed_hosts: es01,es02,es03
      cluster.initial_master_nodes: es01,es02,es03
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/node2/data:/usr/share/elasticsearch/data
    networks:
      - es-net

  es03:
    image: elasticsearch:8.6.2
    container_name: es03
    restart: unless-stopped
    ports:
      - "9202:9200"
      - "9302:9300"
    environment:
      node.name: es03
      cluster.name: docker-cluster
      discovery.seed_hosts: es01,es02,es03
      cluster.initial_master_nodes: es01,es02,es03
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/node3/data:/usr/share/elasticsearch/data
    networks:
      - es-net

  kibana:
    image: kibana:8.6.2
    container_name: kibana
    restart: unless-stopped
    depends_on:
      - es01
      - es02
      - es03
    environment:
      SERVERNAME: kibana
      ES_JAVA_OPTS: -Xmx521m -Xms512m
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    networks:
      - es-net
    ports:
      - "5601:5601"
      - "9600:9600"

networks:
  es-net:
    driver: bridgey
