server:
  port: 9002

spring:
  application:
    name: oauth2-resource-server
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9000
#  cloud:
#    nacos:
#      discovery:
#        # 服务注册地址
#        server-addr: 119.3.188.100:8848
#        service: oauth2-client

  main:
    allow-bean-definition-overriding: true