server:
  port: 3001
spring:
  application:
    name: consumer-service
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 119.3.188.100:8848
        service: consumer-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["*"]
#springdoc相关配置
springdoc:
  swagger-ui:
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/swagger-ui.html会自动重定向到swagger页面
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs    #swagger后端请求地址
    enabled: true   #是否开启文档功能
  group-configs:
    - group: 'consumer-service'
      paths-to-match: '/**'
      packages-to-scan: org.spring.cloud.consumer   #按包路径匹配:一般到启动类的包名

#knife4j相关配置 可以不用改
knife4j:
  enable: true    #开启knife4j，无需添加@EnableKnife4j注解
  setting:
    language: zh_cn   #中文
    #开启Swagger的Basic认证功能,默认是false
    #  basic:
    #    enable: true
    # Basic认证用户名
    #    username: 张乔
    # Basic认证密码
#    password: 123456