server:
  port: 5002
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
springfox:
  documentation:
    auto-startup: false
spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springreport?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: wtf0010.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    initial-size: 50
    min-idle: 50
    max-active: 100
    max-wait: 5000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 50
    filters: stat,wall
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    use-global-data-source-stat: true
    stat-view-servlet.enabled: false
    stat-view-servlet.login-username: admin
    stat-view-servlet.login-password: admin
    stat-view-servlet.allow: ""
    connectionErrorRetryAttempts: 3
    breakAfterAcquireFailure: true
    timeBetweenConnectErrorMillis: 300000
  mail:
    host: smtp.163.com
    username:
    from:
file:
  path: E:\IdeaProjects\springboot3-learning\springboot3-report\springboot3-report-configure\src\main\resources

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
#  mapperLocations:
#    - classpath*:/mapper/**/*.xml

merchantmode: 1
thirdParty:
  type: ruoyi
show:
  report:
    sql: true

authentic:
  enabale: true
#logging:
#  config: classpath:logback.xml