spring:
  application:
    name: springboot3-postgresql

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # ???
      url: jdbc:postgresql://192.168.100.136:5432/postgres
      username: root
      password: root
      driver-class-name: org.postgresql.Driver
      # ???-?????
      initial-size: 10
      # ???-?????
      max-active: 100
      # ??????
      max-wait: 60000
      # ???-?????
      min-idle: 10
      # ??????
      test-while-idle: true
      # ??????
      min-evictable-idle-time-millis: 300000

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml