# Redis分布式锁配置示例
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# 分布式锁配置
vivi:
  redis-lock:
    # 是否启用分布式锁
    enabled: true
    
    # Redis配置
    redis:
      # 锁键前缀
      prefix: "distributed-lock:"
      # 默认过期时间（毫秒）
      default-expire-time: 30000
      # 重试次数
      retry-times: 3
      # 重试间隔（毫秒）
      retry-interval: 100
    
    # 监控配置
    monitor:
      # 是否启用监控
      enabled: true
      # 指标保留时间（毫秒）
      metrics-retention-time: 3600000
    
    # 健康检查配置
    health-check:
      # 是否启用健康检查
      enabled: true
      # 健康检查间隔（毫秒）
      interval: 30000
      # 健康检查超时时间（毫秒）
      timeout: 5000

# 日志配置
logging:
  level:
    org.vivi.redis.lock: DEBUG