springdoc:
  swagger-ui:
    enabled: true
    #path: /swagger-ui.html
    #http://localhost:8000/swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
    syntax-highlight:
      activated: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - display-name: "API"
      group: API
      paths-to-match: org.vivi.spring3
server:
  port: 8001
knife4j:
  enable: true
  documents:
    name: vivi
  setting:
    language: zh_cn
  basic:
    enable: true
#    username: test
#    password: 123456