#!/bin/bash

set -e

## config for sync
MASTER_HOST="${MASTER_HOST:-14.103.123.142}"
MASTER_PORT="${MASTER_PORT:-3307}"
MASTER_SYNC_USER="${MASTER_SYNC_USER:-sync_admin}"
MASTER_SYNC_PASSWORD="${MASTER_SYNC_PASSWORD:-sync_123456}"

SLAVE_ADMIN_USER="root"
SLAVE_ADMIN_PASSWORD="123456"

sleep 10

RESULT=`mysql -h$MASTER_HOST -p$MASTER_PORT -u"$MASTER_SYNC_USER" -p"$MASTER_SYNC_PASSWORD" -e "SHOW MASTER STATUS;" | grep -v grep |tail -n +2| awk '{print $1,$2}'`
LOG_FILE_NAME=`echo $RESULT | grep -v grep | awk '{print $1}'`
LOG_FILE_POS=`echo $RESULT | grep -v grep | awk '{print $2}'`

SYNC_SQL="""
CHANGE REPLICATION SOURCE TO
  SOURCE_HOST='$MASTER_HOST',
  SOURCE_PORT=$MASTER_PORT,
  SOURCE_USER='$MASTER_SYNC_USER',
  SOURCE_PASSWORD='$MASTER_SYNC_PASSWORD',
  SOURCE_LOG_FILE='$LOG_FILE_NAME',
  SOURCE_LOG_POS=$LOG_FILE_POS,
  SOURCE_CONNECT_RETRY=10;
"""
START_SYNC_SQL="START REPLICA;"
STATUS_SQL="SHOW REPLICA STATUS\G;"

mysql -u"$SLAVE_ADMIN_USER" -p"$SLAVE_ADMIN_PASSWORD" -e "$SYNC_SQL"
mysql -u"$SLAVE_ADMIN_USER" -p"$SLAVE_ADMIN_PASSWORD" -e "$START_SYNC_SQL"
mysql -u"$SLAVE_ADMIN_USER" -p"$SLAVE_ADMIN_PASSWORD" -e "$STATUS_SQL"
