spring:
  application:
    name: springboot3-minio
minio:
  endpoint: http://14.103.123.142:9000
  access-key: root
  secret-key: root1234
  bucket-name: blog

springdoc:
  group-configs:
    - group: "demo"
      paths-to-match:
        - /demo/**
    - group: "public"
      paths-to-match:
        - /public/**
  packages-to-scan: org.vivi.framework
