server:
  port: 1002
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 119.3.188.100:8848
    gateway:
      #gateway 定义路由转发规则
      routes:
        #一份设定
        - id: route1   #唯一标识
          uri: lb://nacos-discovery-provider  #访问的路径，lb://负载均衡访问固定写法，通过负载均衡调取所有设定中的一份
          predicates: #谓词，判断，是否匹配。用户请求的路径是否与...进行匹配，如果匹配则可以访问，否则就404
            - Path=/provider/**,/index/**

