# 可参考 https://docs.min.io/docs/minio-docker-quickstart-guide.html
version: '3'
services:
#  minio:
#    image: minio/minio:RELEASE.2025-04-03T14-56-28Z                                    # 原镜像`minio/minio:latest`
#    container_name: minio                                        # 容器名为'minio'
#    restart: unless-stopped                                              # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
#    volumes:                                                     # 数据卷挂载路径设置,将本机目录映射到容器目录
#      - "./minio/data:/data"
#      - "./minio/minio:/minio"
#      - "./minio/config:/root/.minio"
#    environment:                                      # 设置环境变量,相当于docker run命令中的-e
#      TZ: Asia/Shanghai
#      LANG: en_US.UTF-8
#      MINIO_PROMETHEUS_AUTH_TYPE: "public"
#      MINIO_ACCESS_KEY: "root"                        # 登录账号
#      MINIO_SECRET_KEY: "root1234"                    # 登录密码
#    command: server --address ':9000' --console-address ':9001' /data  # 指定容器中的目录 /data
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100m"
#    ports:                              # 映射端口
#      - "9000:9000" # 文件上传&预览端口
#      - "9001:9001" # 控制台访问端口
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"  # API端口
      - "9001:9001"  # 控制台端口
    environment:
      - MINIO_ROOT_USER=admin        # 必须修改，不再使用默认minioadmin
      - MINIO_ROOT_PASSWORD=root1234!  # 必须修改为强密码
      - MINIO_BROWSER=on             # 启用Web控制台
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./minio/data:/data"
      - "./minio/minio:/minio"
      - "./minio/config:/root/.minio"
    command: server --address ':9000' --console-address ':9001' /data  # 指定容器中的目录 /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://14.103.123.142:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped