server:
  port: 9004
  servlet:
    session:
      cookie:
        name: JSESSIONID-4

logging:
  level:
    org.springframework.security: trace
spring:
  application:
    name: springboot3-oauth-product
  security:
    oauth2:
      client:
        provider:
          oauth-server:
            issuer-uri: http://localhost:9000
            authorizationUri: ${spring.security.oauth2.client.provider.oauth-server.issuer-uri}/oauth2/authorize
            tokenUri: ${spring.security.oauth2.client.provider.oauth-server.issuer-uri}/oauth2/token
        registration:
          messaging-client-oidc:
            provider: oauth-server
            client-name: web平台-SSO客户端-商品服务
            client-id: web-client-id-product
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9004/login/oauth2/code/messaging-client-oidc
            scope:
              - profile
              - openid
