spring:
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: classpath:/static
  application:
    name: springboot3-ureport-store
  mvc:
    static-path-pattern: /static/**
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      connect-timeout: 300000
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aoye?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: wtf0010.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-circular-references: true

ureport:
  disableHttpSessionReportCache: false
  # ??????????
  disableFileProvider: true
  fileStoreDir: ureportfiles
  debug: true
  # ????redis????
  enableRedis: false
  # redis?????? (?????) ??60??
  cacheExpire: 60
  # ?????????
  ossEnable: false
  # ?????
  oss:
    # ???????
    endpoint:
    # ???key
    access-key:
    # ?????
    secret-key:
    # ???
    bucket-name:
    # ?????????
    region:
    # ??????
    max-connections: 100
    # ???????
    prefix: source/report/

    ############## Sa-Token ?? (??: https://sa-token.cc) ##############
  sa-token:
    # token?? (????cookie??)
    token-name: satoken
    # token??????s ??30?, -1??????
    timeout: 2592000
    # token????? (???????????token??) ??: ?
    activity-timeout: -1
    # ???????????? (?true???????, ?false?????????)
    is-concurrent: true
    # ?????????????????token (?true?????????token, ?false?????????token)
    is-share: true
    # token??
    token-style: uuid
    # ????????
    is-log: false
mybatis-plus:
  type-aliases-package: org.vivi.framework.ureport.store.domain
